version: "3.9"

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=psqldb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    depends_on:
      - psql

  psql:
    restart: always
    image: postgres
    container_name: psqldb
    volumes:
      - psqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=psqldb
    ports:
      - 5432:5432
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    volumes:
      - pgadmindata:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=panuvit.chantara@ait.asia
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80
    depends_on:
      - psql

volumes:
  pgadmindata:
  psqldata: